### ISSUE TITLE
Not loading an unlimited profile

### ISSUE THREAD

**Issue by RobbieTechie** [ElJaviLuki/GrindrPlus#1]
Almost everything works as one would expect, but when clicking on a profile in the Unlimited section, it loads the very first profile in the grid instead.  Everything in the xtra section will load a profile properly, after that only the very first profile loads, meaning that clicking a profile in an Unlimited section loads the very first profile of the entire grid.  Watching the API, it doesn't appear there is even an attempt to fetch the profile data if you are past the xtra section and inside the unlimited area.

**Comment by ElJaviLuki** [comment]
Certainly it's possible to fix that but it would imply dealing with obfuscated code, which although it's not hard to understand, hooking the proper methods by referencing them with their obfuscated names is just crazy, as obfuscation is likely to change for each update of the Android client. Maybe there's a workaround I cannot see yet.

Actually, there's lots of modifiable features in the Grindr client but I haven't implemented these mods because it would involve dealing with obfuscated code: that means, dealing with ugly and likely-to-change code.

**Comment by RobbieTechie** [comment]
I've noticed that, while digging through it a bit.  I use to help with a client called Fuckr, that was popular a few years back.  Grindr panicked while that was out and went after it, and the Github repo was taken down, I would call that censorship.  I'm somewhat familiar with their API from helping with that project.  They use to heavily obfuscate the code rather than just using meaningless names, at which point apk-deguard became somewhat helpful ;) 

I do know the sessions control unlocking features, they are base64 encoded and are attached to the Authorization header, here is a decoded example with a bit cut out
{"typ":"JWT","alg":"HS256"}{"features":["Subscriber","HideBannerAds","HideFullScreenAds","UnlimitedFavorites","UnlimitedBlocks","UnlimitedExpiringPhotos","MyTypeFilters","PhotosOnlyFilter","OnlineNowFilter","HaventChattedFilter","ChatDeliveryStatus","ChatRemoteProfiles","TapRemoteProfiles","SavedPhrases","HaveChattedHighlight","DiscreetIcon","PINLock","TapFilters","SendMultiplePics","PushSnoozing","PushPreview","MoreChatGroups","LastChattedTimestamp","ChatReadStatus","BlockRemoteProfiles","FavoriteRemoteProfiles","PriorityPhotoModeration","MultiTribes","VideoCallMonthlyCalculateLengthHigh","CreateVideoCall","LongBlocklist","WebChat","Incognito","UnlimitedCascade","ViewedMeCascade","ViewedMeTimestamp","FaceOnlyFilter","UnsentMessage","TypingIndicator","TranslateMessage","HideXtraStore","HideUnlimitedStore","HideBroadcastMessages","FreeTrial"],"profileId":"REDACTED","roles":["Unlimited"],"exp":REDACTED}izÈ#0зQY4;#U^Sk

This was from the spring of 2020 so I'm sure some has changed, but one can see how this relates to unlocking features.

Anyways, maybe this might help in future work
Thank you for sharing your code, I will close this issue now that I'm aware of where things stand, I hope you have a great day.
