### ISSUE TITLE
Hooking version 8.11 no longer works

### ISSUE THREAD

**Issue by Fernando08RF** [ElJaviLuki/GrindrPlus#14]
version 8.11 no longer works, ask for a mandatory update

**Comment by jason5591** [comment]
Yes, sad day. But I'm sure will be fixed as soon as he has time.

**Comment by zsantino** [comment]
I confirm, same problem.

**Comment by robersdk** [comment]
Same here

**Comment by Lanchon** [comment]
https://github.com/Lanchon/GrindrPlus/releases/tag/8.16.0-1

warning: the original dev might be working on an official port to a grindr version < 8.16: take a backup before upgrading grindr!

**Comment by Zarkoob** [comment]
> Now you should be able to use v8.16, no official build of the hook is made yet though.

 @ElJaviLuki as of the latest commit [a822f0f](https://github.com/ElJaviLuki/GrindrPlus/commit/a822f0f289bfe7ae46b2c5f6b5a0d45801105dc4) it is working with v8.16! 🎉🥳... 
 however, the favorites tab shows incorrect or dupe pics of other dudes. No fuctionality breaking from what I can tell. Not sure how to go about reporting that one. A point in the right direction would be appreciated. 

Happy to help test and from all of us thanks for your work on this! 😘🥇

**Comment by Lanchon** [comment]
this issue should be closed.

@Zarkoob the fav tab shows correct pics for profiles that have pics. for profiles that don't, i shows "random" pics. this is quite possibly a grindr app bug.

in any case, please never hijack an existing issue. always create a new issue if you want to report, well, a new issue. in this case you probably should disable plus and check whether it happens without plus before reporting.

**Comment by Lanchon** [comment]
@ElJaviLuki please close this
