### ISSUE TITLE
Filters not working

### ISSUE THREAD

**Issue by secrj** [ElJaviLuki/GrindrPlus#25]
You can choose filters but they aren't working correctly. At least the online now doesn't

**Comment by RobbieTechie** [comment]
https://github.com/ElJaviLuki/GrindrPlus/issues/12

**Comment by RobbieTechie** [comment]
> You can choose filters but they aren't working correctly. At least the online now doesn't

https://github.com/ElJaviLuki/GrindrPlus/issues/12

**Comment by Lanchon** [comment]
please close this dup
