### ISSUE TITLE
Sugestion: Bypass Device Ban

### ISSUE THREAD

**Issue by Aferallan** [ElJaviLuki/GrindrPlus#35]
It's been a while since I was banned from grindr, and to this day I still do not know the reason, since they say I broke a rule, which? do not quote.

And I wanted to circumvent the ban, I tried some xposed modules to circumvent the deviceid and everything else, but to no avail.

I imagine that they use the IMEI to ban the device, then it would be good if there was a function to circumvent this through the module itself

**Comment by ProfessionalMD5** [comment]
Use a module named XPrivacyLua. Add Grindr to its scope in Xposed app, then open the app and tick "Read Identifiers" for Grindr; that will hide your HWID from the app.

**Comment by Lanchon** [comment]
last time i checked, grindr won't like it when you create an account with a bootloader unlocked phone/rooted phone/custom rom phone. try creating the account with a stock phone, then move it to your phone.

**Comment by Aferallan** [comment]
It Worked

Use a module named XPrivacyLua. Add Grindr to its scope in Xposed app, then open the app and tick "Read Identifiers" for Grindr; that will hide your HWID from the app.
