### ISSUE TITLE
> > Grindr Xtra e ilimitado te permite crear hasta 10 álbumes, ¿es posible agregar esta función al mod? Sería más cómodo enviar un álbum según el rol de la otra persona, así no muestro todo🤭😂😂

### ISSUE THREAD

**Issue by pavelchum** [ElJaviLuki/GrindrPlus#39]
> > Grindr Xtra e ilimitado te permite crear hasta 10 álbumes, ¿es posible agregar esta función al mod? Sería más cómodo enviar un álbum según el rol de la otra persona, así no muestro todo🤭😂😂
> 
> Todo es posible si puedes codificarlo, amigo mío. ¿Por qué no contribuyes?😉

Si supiera me encantaría ayudar jsjsj pero de por sí mi inglés es muy limitado como para poder codificar jsjsjs

_Originally posted by @matias200308 in https://github.com/ElJaviLuki/GrindrPlus/issues/21#issuecomment-1252801922_

**Comment by pavelchum** [comment]
> ```
>     > > Grindr Xtra e ilimitado te permite crear hasta 10 álbumes, ¿es posible agregar esta función al mod? Sería más cómodo enviar un álbum según el rol de la otra persona, así no muestro todo🤭😂😂
> ```
> 
> > Todo es posible si puedes codificarlo, amigo mío. ¿Por qué no contribuyes?😉
> 
> Si supiera me encantaría ayudar jsjsj pero de por sí mi inglés es muy limitado como para poder codificar jsjsjs
> 
> _Originally posted by @matias200308 in [#21 (comment)](https://github.com/ElJaviLuki/GrindrPlus/issues/21#issuecomment-1252801922)_

**Comment by ElJaviLuki** [comment]
This is not a platform for casual conversation or discussing unrelated topics, like ForoCoches or Twitter. Please refrain from posting non-issue related content and stick to the purpose of this section, which is to report and address issues related to Grindr Plus. Please also remember to use English as the official language of communication on GitHub.
