### ISSUE TITLE
App should be updated, as Grindr forces 9.7.0 update

### ISSUE THREAD

**Issue by ProfessionalMD5** [ElJaviLuki/GrindrPlus#44]
Grindr is painful to be used without this app! Please help us 😭🙏🏻!

**Comment by ElJaviLuki** [comment]
I can't test new versions since I changed my phone and no longer have Xposed nor I expect to have it installed soon.
Besides, this is so time-consuming

**Comment by ProfessionalMD5** [comment]
> I can't test new versions since I changed my phone and no longer have Xposed nor I expect to have it installed soon. Besides, this is so time-consuming

@ElJaviLuki, any documentation you can provide that is particular useful to help people continue this project?
I would love to put my hands on it :).
Maybe @Lanchon could provide some help too?

**Comment by RobbieTechie** [comment]
As far as Xposed and devices, one could always test on an emulator such as Nox or one of the others if you wish to not root your new phone.  Even Bluestacks can be rooted, but not the most recent version....

As far as time, that's another story... 🙃

**Comment by RobbieTechie** [comment]
@ProfessionalMD5 were you able to build yourself a working version?

**Comment by ProfessionalMD5** [comment]
> @ProfessionalMD5 were you able to build yourself a working version?

Yup; i built the one from TebbeUbben fork!

**Comment by Marukoalitini** [comment]
> > @ProfessionalMD5 were you able to build yourself a working version?
> 
> Yup; i built the one from TebbeUbben fork!

how can I build a working version myself?

**Comment by ProfessionalMD5** [comment]
> > > @ProfessionalMD5 were you able to build yourself a working version?
> > 
> > 
> > Yup; i built the one from TebbeUbben fork!
> 
> how can I build a working version myself?

You have to download Android Studio in your computer, then clone this repo using the terminal command "git clone (repo url)", which needs the software "git" to be installed for it to work. 

Then in Android Studio you got to open this project folder and in Build menu you can build the debug unsigned APK and then install it to your phone.

**Comment by Sambatester** [comment]
How do I install the updated version? I'm new pls

**Comment by Sambatester** [comment]
@TebbeUbben  how do install the new version please. I'm quite new

**Comment by Lanchon** [comment]
hey,

so im still using 9.2.0 and i don't get any forced update roadblocks. last time was the same: i decided to update on my own due to FOMO of latest features, while people had been long complaining about forced updates that i didn't get.

anybody has a clue of why this could be?

**Comment by ProfessionalMD5** [comment]
Resolved
