### ISSUE TITLE
Can anyone help with to get it working?

### ISSUE THREAD

**Issue by Sambatester** [ElJaviLuki/GrindrPlus#48]
I'm sure most of you know how to get Grindr back up and running from the Pull request but I feel me and some others are sadly left behind as we honestly don't have a clue what to do. Is anyone kind enough to help out on how to get it working? I'm currently on 9.6.0

I would highly appreciate this and others too!

**Comment by ElJaviLuki** [comment]
Later I'll upload a new release

**Comment by Sambatester** [comment]
When is the release?

**Comment by ElJaviLuki** [comment]
https://github.com/ElJaviLuki/GrindrPlus/releases/tag/v1.2.5-9.9.1
